// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Swag', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    // Test name: Login
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.saucedemo.com/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | css=*[data-test="username"] | 
    await driver.findElement(By.css("*[data-test=\"username\"]")).click()
    // 4 | type | css=*[data-test="username"] | standard_user
    await driver.findElement(By.css("*[data-test=\"username\"]")).sendKeys("standard_user")
    // 5 | click | css=*[data-test="password"] | 
    await driver.findElement(By.css("*[data-test=\"password\"]")).click()
    // 6 | type | css=*[data-test="password"] | secret_sauce
    await driver.findElement(By.css("*[data-test=\"password\"]")).sendKeys("secret_sauce")
    // 7 | click | css=*[data-test="login-button"] | 
    await driver.findElement(By.css("*[data-test=\"login-button\"]")).click()
  })
  it('select_and_goto_details', async function() {
    // Test name: select_and_goto_details
    // Step # | name | target | value
    // 1 | click | css=#item_5_title_link > .inventory_item_name | 
    await driver.findElement(By.css("#item_5_title_link > .inventory_item_name")).click()
  })
  it('Add_to_cart', async function() {
    // Test name: Add_to_cart
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.saucedemo.com/")
    // 2 | setWindowSize | 791x650 | 
    await driver.manage().window().setRect({ width: 791, height: 650 })
    // 3 | click | css=*[data-test="username"] | 
    await driver.findElement(By.css("*[data-test=\"username\"]")).click()
    // 4 | type | css=*[data-test="username"] | standard_user
    await driver.findElement(By.css("*[data-test=\"username\"]")).sendKeys("standard_user")
    // 5 | click | css=*[data-test="password"] | 
    await driver.findElement(By.css("*[data-test=\"password\"]")).click()
    // 6 | type | css=*[data-test="password"] | secret_sauce
    await driver.findElement(By.css("*[data-test=\"password\"]")).sendKeys("secret_sauce")
    // 7 | click | css=*[data-test="login-button"] | 
    await driver.findElement(By.css("*[data-test=\"login-button\"]")).click()
    // 8 | click | css=#item_5_title_link > .inventory_item_name | 
    await driver.findElement(By.css("#item_5_title_link > .inventory_item_name")).click()
    // 9 | click | css=*[data-test="add-to-cart"] | 
    await driver.findElement(By.css("*[data-test=\"add-to-cart\"]")).click()
  })
  it('Go_to_cart', async function() {
    // Test name: Go_to_cart
    // Step # | name | target | value
    // 1 | click | css=*[data-test="shopping-cart-link"] | 
    await driver.findElement(By.css("*[data-test=\"shopping-cart-link\"]")).click()
  })
  it('Proceed_To_Checkout', async function() {
    // Test name: Proceed_To_Checkout
    // Step # | name | target | value
  })
  it('Enter_Checkout_Information', async function() {
    // Test name: Enter_Checkout_Information
    // Step # | name | target | value
  })
  it('Print_Payment_Information', async function() {
    // Test name: Print_Payment_Information
    // Step # | name | target | value
  })
  it('Finish_Purchase', async function() {
    // Test name: Finish_Purchase
    // Step # | name | target | value
  })
})
